---
abstract: 'Language detection for Catalyst::Requests'
author:
  - 'Stephan Jauernick <stephan@stejau.de>'
build_requires:
  Catalyst::Action::RenderView: 0
  Catalyst::Plugin::Session: 0
  Catalyst::Plugin::Session::State::Cookie: 0
  Catalyst::Plugin::Session::Store::File: 0
  Catalyst::View::TT: 0
  CatalystX::RoleApplicator: 0
  ExtUtils::MakeMaker: 6.42
  HTTP::Request::Common: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.99'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-TraitFor-Request-PerLanguageDomains
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst: 5.80
  I18N::AcceptLanguage: 0
  Moose: 0
  Moose::Autobox: 0
  MooseX::Types: 0
  MooseX::Types::Common::String: 0
  MooseX::Types::Structured: 0
  namespace::autoclean: 0
  perl: 5.8.5
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/stephan48/Catalyst-TraitFor-Request-PerLanguageDomains/
version: 0.03
